
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as Total_Revenue
from customer_behavior_table
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id ,purchase_amount ,discount_applied
from customer_behavior_table
where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount) from customer_behavior_table);



-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(AVG(review_rating),2) as Highest_Average_Review_Rating
from customer_behavior_table
group by  item_purchased
order by avg(review_rating) desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
round(AVG(purchase_amount),2) as Average_Purchase_Amount
from customer_behavior_table
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
	COUNT(customer_id) as Total_Customers,
	ROUND(Avg(purchase_amount),2) as Avg_Spend,
	ROUND(sum(purchase_amount),2) as Total_Revenue
from customer_behavior_table
group by subscription_status
order by Total_Revenue , Avg_Spend Desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select Top 5 item_purchased,
	ROUND(100.0 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as Discount_Rate
from customer_behavior_table
group by item_purchased
order by Discount_Rate desc;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
end as Customer_Segment
from customer_behavior_table
)
select Customer_Segment,COUNT(*) as 'Number of Customers'
from customer_type
group by Customer_Segment;


--Q8. What are the top 3 most purchased products within each category? 
With item_counts as (
Select category,
item_purchased , COUNT(customer_id) as Total_Orders,
ROW_NUMBER() over(Partition By Category Order by Count(customer_id)Desc) as item_rank
from customer_behavior_table
group by category, item_purchased
)
select item_rank,category,item_purchased,Total_Orders
from item_counts
where item_rank <=3; 


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer_behavior_table
where previous_purchases >5
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group,SUM(purchase_amount) as total_revenue
from customer_behavior_table
group by age_group
order by total_revenue desc;
